### ISSUE TITLE
Expo on my android crash after adding an animation

### ISSUE THREAD

**Issue by lionel95200x** [airbnb/lottie-react-native#151]
Hello
I have just adding a simple animation to my project with the basic exemple
On my ios simulator all it's ok, the animation work
But when i build app on my android device (Galaxy S8) expo crashes instantly
I have type command : react-native link lottie-react-native

Do you have any solutions or suggestions ?

**Comment by gpeal** [comment]
@lionel95200x Can you post the crash stack from logcat?

**Comment by ErhanKaraca** [comment]
can anyone find a solution about this issue?

**Comment by gpeal** [comment]
@ErhanKaraca I can't fix this without a stack trace.

**Comment by donedgardo** [comment]
```
09-15 20:39:50.082 E/AndroidRuntime( 1934): FATAL EXCEPTION: main
09-15 20:39:50.082 E/AndroidRuntime( 1934): Process: host.exp.exponent, PID: 1934
09-15 20:39:50.082 E/AndroidRuntime( 1934): java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.bu.a(ImageAssetBitmapManager.java:70)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.cp.b(LottieDrawable.java:436)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.bw.f(ImageLayer.java:57)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.bw.b(ImageLayer.java:26)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.al.a(BaseLayer.java:161)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.ax.b(CompositionLayer.java:56)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.al.a(BaseLayer.java:161)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.airbnb.lottie.cp.draw(LottieDrawable.java:287)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.widget.ImageView.onDraw(ImageView.java:1316)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.draw(View.java:17185)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.buildDrawingCacheImpl(View.java:16474)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.buildDrawingCache(View.java:16335)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.draw(View.java:16943)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.draw(View.java:17188)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.updateDisplayListIfDirty(View.java:16167)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.draw(View.java:16951)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.updateDisplayListIfDirty(View.java:16162)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.Choreographer.doFrame(Choreographer.java:621)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.os.Handler.handleCallback(Handler.java:751)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.os.Looper.loop(Looper.java:154)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at java.lang.reflect.Method.invoke(Native Method)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
09-15 20:39:50.082 E/AndroidRuntime( 1934): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-15 20:39:50.083 W/ActivityManager(  584):   Force finishing activity host.exp.exponent/.experience.ExperienceActivity
09-15 20:39:50.129 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:50.133 D/        (  584): HostConnection::get() New Host Connection established 0xd0323f80, tid 2056
09-15 20:39:50.135 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:50.139 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:50.167 I/OpenGLRenderer(  584): Initialized EGL, version 1.4
09-15 20:39:50.167 D/OpenGLRenderer(  584): Swap behavior 1
09-15 20:39:50.198 E/EGL_emulation(  584): tid 2056: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
09-15 20:39:50.198 W/OpenGLRenderer(  584): Failed to set EGL_SWAP_BEHAVIOR on surface 0xca5b0000, error=EGL_BAD_MATCH
09-15 20:39:50.466 I/ReactNativeJS( 1934): Connected to DDP server.
09-15 20:39:50.485 I/CrashlyticsCore( 1934): Crashlytics report upload complete: 59BC72BC0348-0001-078E-84713AA26F2A.cls
09-15 20:39:50.585 W/ActivityManager(  584): Activity pause timeout for ActivityRecord{69ce992 u0 host.exp.exponent/.experience.ExperienceActivity t30 f}
09-15 20:39:50.626 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
09-15 20:39:50.633 D/        (  584): HostConnection::get() New Host Connection established 0xe1cd3180, tid 598
09-15 20:39:50.687 E/EGL_emulation(  320): tid 320: eglCreateSyncKHR(1669): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-15 20:39:50.808 W/art     (  584): Long monitor contention with owner ActivityManager (598) at android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplicationsInner(android.os.IBinder, int, int, int, boolean, float, android.graphics.Bitmap$Config, boolean)(WindowManagerService.java:6462) waiters=0 in void com.android.server.wm.WindowAnimator$1.doFrame(long) for 213ms
09-15 20:39:50.810 W/art     (  584): Long monitor contention with owner ActivityManager (598) at android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplicationsInner(android.os.IBinder, int, int, int, boolean, float, android.graphics.Bitmap$Config, boolean)(WindowManagerService.java:6462) waiters=1 in int com.android.server.wm.WindowManagerService.relayoutWindow(com.android.server.wm.Session, android.view.IWindow, int, android.view.WindowManager$LayoutParams, int, int, int, int, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.content.res.Configuration, android.view.Surface) for 212ms
09-15 20:39:50.865 W/art     (  584): Long monitor contention with owner ActivityManager (598) at void com.android.server.am.ActivityStack$ActivityStackHandler.handleMessage(android.os.Message)(ActivityStack.java:373) waiters=0 in void com.android.server.am.ActivityManagerService.dispatchProcessesChanged() for 270ms
09-15 20:39:50.899 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:50.912 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:50.923 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:50.936 E/EGL_emulation( 1042): tid 1179: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
09-15 20:39:50.936 W/OpenGLRenderer( 1042): Failed to set EGL_SWAP_BEHAVIOR on surface 0xd12fe320, error=EGL_BAD_MATCH
09-15 20:39:51.461 W/OpenGLRenderer( 1042): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-15 20:39:57.637 W/ActivityManager(  584):   Force finishing activity host.exp.exponent/.experience.ExperienceActivity
09-15 20:39:57.649 I/ActivityManager(  584): Killing 1934:host.exp.exponent/u0a64 (adj 900): crash
09-15 20:39:57.649 D/ActivityManager(  584): cleanUpApplicationRecord -- 1934
09-15 20:39:57.681 D/GraphicsStats(  584): Buffer count: 4
09-15 20:39:57.682 W/InputEventReceiver(  584): Attempted to finish an input event but the input event receiver has already been disposed.
09-15 20:39:57.893 W/AppOps  (  584): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-15 20:39:59.809 I/PowerManagerService(  584): Going to sleep due to power button (uid 1000)...
09-15 20:39:59.809 I/PowerManagerService(  584): Sleeping (uid 1000)...
09-15 20:39:59.813 W/FingerprintManager(  678): isFingerprintHardwareDetected(): Service not connected!
09-15 20:39:59.828 D/        (  584): HostConnection::get() New Host Connection established 0xcd330840, tid 607
09-15 20:39:59.860 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:59.879 E/EGL_emulation(  584): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
09-15 20:39:59.879 E/EGL_emulation(  584): tid 607: eglQueryContext(1484): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-15 20:39:59.880 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
09-15 20:39:59.925 E/EGL_emulation(  320): tid 320: eglCreateSyncKHR(1669): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-15 20:39:59.964 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:39:59.982 D/gralloc_vbox86(  320): gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-15 20:40:00.418 V/KeyguardServiceDelegate(  584): onScreenTurnedOff()
09-15 20:40:00.423 E/libEGL  (  584): call to OpenGL ES API with no current context (logged once per thread)
09-15 20:40:00.424 I/DisplayManagerService(  584): Display device changed state: "Built-in Screen", OFF
09-15 20:40:00.424 D/SurfaceFlinger(  320): Set power mode=0, type=0 flinger=0xf50b0000
09-15 20:40:00.424 E/libsuspend(  584): Error writing to /sys/power/autosleep: Invalid argument
09-15 20:40:00.428 E/SupplicantWifiScannerImpl(  584): Failed to start scan, freqs={2412}
09-15 20:40:00.428 E/WifiConnectivityManager(  584): SingleScanListener onFailure: reason: -1 description: Scan failed
09-15 20:40:00.429 W/FingerprintManager(  678): isFingerprintHardwareDetected(): Service not connected!
```

**Comment by gpeal** [comment]
@donedgardo Your animations does require images. It may not be intentional though. If you imported layers from Illustrator, make sure to convert them to shape layers.
