### ISSUE TITLE
[Android] Crash on opening animation

### ISSUE THREAD

**Issue by Bhullnatik** [airbnb/lottie-react-native#154]
Hey,

I have a crash when using this library when opening a specific animation. I'm not sure where it is coming from, and I haven't tried with `lottie-android` but it seems to come from a class used only in `lottie-react-native`.

Find attached the related json. If I can provide any more informations let me know.

React-native version: 0.46.2
lottie-react-native version: 1.2.0

[miam.json.zip](https://github.com/airbnb/lottie-react-native/files/1160717/miam.json.zip)

<details>
<summary>Stacktrace Android</summary>

```java
07-19 19:39:03.280 14711-16152/**** E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                                  Process: ****, PID: 14711
                                                                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                      at java.lang.Thread.run(Thread.java:761)
                                                                   Caused by: java.lang.UnsupportedOperationException: JSONReadableMap does not implement this method
                                                                      at com.airbnb.android.react.lottie.JSONReadableMap.put(JSONReadableMap.java:70)
                                                                      at com.airbnb.lottie.GradientFill$Factory.newInstance(GradientFill.java:91)
                                                                      at com.airbnb.lottie.ShapeGroup.shapeItemWithJson(ShapeGroup.java:27)
                                                                      at com.airbnb.lottie.ShapeGroup$Factory.newInstance(ShapeGroup.java:68)
                                                                      at com.airbnb.lottie.ShapeGroup$Factory.access$000(ShapeGroup.java:58)
                                                                      at com.airbnb.lottie.ShapeGroup.shapeItemWithJson(ShapeGroup.java:19)
                                                                      at com.airbnb.lottie.Layer$Factory.newInstance(Layer.java:275)
                                                                      at com.airbnb.lottie.LottieComposition$Factory.parsePrecomps(LottieComposition.java:312)
                                                                      at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:264)
                                                                      at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:17)
                                                                      at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:7)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                      at java.lang.Thread.run(Thread.java:761)
```

</details>

**Comment by mitch104** [comment]
I had a similar issue which has been temporarily resolved by downgrading the lottie-react-native version 1.1.1. I am on react-native version 0.46.4.

**Comment by gpeal** [comment]
@mitch104 can you attach an animation that repros this?

**Comment by fermuch** [comment]
@gpeal [this](https://gist.github.com/fermuch/0be552bdd35567af13deb3f7971ada9d) animation causes a crash. It even crashes the Lottie Preview app.

**Comment by fermuch** [comment]
As an update, this still happens with `lottie-react-native@2.2.0` and Lottie Preview App 2.2.1.

**Comment by gpeal** [comment]
@Bhullnatik @mitch104 I just tried that animation on master and it works.

@fermuch Your crash is different. Can you post it on lottie-android? Also, try saving your AE project and re-exporting it.
