### ISSUE TITLE
Adnroid - LottieAnimationView cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by daywong1119** [airbnb/lottie-react-native#186]
Hey,

I tried to build my android app with this repo, I got `com.airbnb.lottie.LottieAnimationView cannot be cast to android.view.ViewGroup`.

`lottie-react-native` is included in gradle file.

Does any one know how to fix this ? 

````
java.lang.ClassCastException: com.airbnb.lottie.LottieAnimationView cannot be cast to android.view.ViewGroup
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:314)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:768)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:824)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:48)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:549)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)````

**Comment by gpeal** [comment]
@daywong1119 Can you attach a sample project that repros this? Other people don't seem to have this issue.

**Comment by gpeal** [comment]
@daywong1119 Also make sure you add the LottiePackage in getPackages in your ReactApplication
```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new LottiePackage()
      );
    }
```

**Comment by anton6** [comment]
I get this error when I am trying to do this on android: `<LottieView>{child}</LottieView>`

On iOS this works fine.

**Comment by daywong1119** [comment]
Now I changed the hierarchy to avoid child element inside <LottieView>, it works fine.

**Comment by mark-quinn** [comment]
> I get this error when I am trying to do this on Android: `<LottieView>{child}</LottieView>`
> 
> On iOS this works fine.

I'm still getting this error with RN version 0.61.5 and lottie-react-native version 3.3.2. Having child elements on iOS works fine but on Android I'm getting this error.

**Comment by sleekLancelot** [comment]
Hi guys, anyone found a solution for this yet?
