### ISSUE TITLE
App crashing on Android after Garbage Collector

### ISSUE THREAD

**Issue by z4o4z** [airbnb/lottie-react-native#202]
Hi, everyone.
This library is very cool and we are trying to use it for our animations, but the app crashes after some animations.

We are using 2 instances of Lottie on one screen. We play the 'animation-1' in the first instance some time then stop it and run the 'animation-2' in the second instance. At the end 'animation-2' we are running 'animation-3' in the first instance.

We are repeating this flow during 10 minutes.

 After some debugging we think that the problem connected with the garbage collector (this lib use lots of memory for each animation step and GC starts killing some objects which still needs for the animations).

After this message:
```
28994-29015/com.react I/art: Background sticky concurrent mark sweep GC freed 357169(9MB) AllocSpace objects, 0(0B) LOS objects, 24% free, 30MB/40MB, paused 758us total 120.801ms
28994-28994/com.react I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
```

The app crashes with error:

```
3164-3164/com.react D/AndroidRuntime: Shutting down VM
3164-3164/com.react E/AndroidRuntime: FATAL EXCEPTION: main
                                                         Process: com.react, PID: 3164
                                                         java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
                                                             at java.util.ArrayList.get(ArrayList.java:411)
                                                             at com.airbnb.lottie.model.content.ShapeData.interpolateBetween(ShapeData.java:77)
                                                             at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:23)
                                                             at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:11)
                                                             at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:112)
                                                             at com.airbnb.lottie.animation.content.ShapeContent.getPath(ShapeContent.java:61)
                                                             at com.airbnb.lottie.animation.content.GradientFillContent.draw(GradientFillContent.java:90)
                                                             at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:174)
                                                             at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:174)
                                                             at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:29)
                                                             at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:187)
                                                             at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:90)
                                                             at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:187)
                                                             at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:343)
                                                             at android.widget.ImageView.onDraw(ImageView.java:1286)
                                                             at android.view.View.draw(View.java:18319)
                                                             at android.view.View.buildDrawingCacheImpl(View.java:17604)
                                                             at android.view.View.buildDrawingCache(View.java:17465)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17278)
                                                             at android.view.View.draw(View.java:18081)
                                                             at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
                                                             at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17292)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                             at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:3112)
                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2908)
                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2502)
                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1509)
                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7051)
3164-3164/com.react E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                             at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:154)
                                                             at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by gpeal** [comment]
@z4o4z Can you attach your animation? This has nothing to do with the GC btw.

**Comment by gpeal** [comment]
@z4o4z If this is still an issue with the latest version, can you open this issue on lottie-android?
