### ISSUE TITLE
Cannot `npm start`

### ISSUE THREAD

**Issue by hoangpham95** [airbnb/lottie-react-native#34]
I tried to run `npm start` but the packager report an error:
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: deprecated
  Paths: /Users/hoangpham/Documents/lottie-react-native/node_modules/react-native/local-cli/server/middleware/heapCapture/bundle.js collides with /Users/hoangpham/Documents/lottie-react-native/node_modules/react-native/Libraries/Renderer/src/shared/utils/deprecated.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: deprecated
  Paths: /Users/hoangpham/Documents/lottie-react-native/node_modules/react-native/local-cli/server/middleware/heapCapture/bundle.js collides with /Users/hoangpham/Documents/lottie-react-native/node_modules/react-native/Libraries/Renderer/src/shared/utils/deprecated.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/hoangpham/Documents/lottie-react-native/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at /Users/hoangpham/Documents/lottie-react-native/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:119:31
```

**Comment by lelandrichardson** [comment]
@hoangpham95 please track this issue in #29 thanks!
