### ISSUE TITLE
App crashes everytime when trying to display lottie animation

### ISSUE THREAD

**Issue by nehvaleem** [airbnb/lottie-react-native#92]
Hi,
I am facing a strange issue. My application crashes everytime when I try to display lottie animation. It works fine on iOS but on Android it fails. I've had some troubles before I could even compile it correctly because I was using `compilesdk 23` and it turns out it has to be at least 24. Idk if it applies to buld tools or support library (I've testes with compilesdk 24, build tools 24.0.1 and support library also 24 - still no luck).

When I try to display lottie my app force crashes. Below is the stack trace when it does. It looks like a problem with null reference to Json file, but I've tried with local json (via require) wchich works fine on iOS and also with remote source `{ uri: 'http://blahblahblah'}`.  I've tested it also with my custom animation and those from examples - still crashes. 

My sample .json file is available on [example.json](http://undefined.com.pl/example.json) (works fine on iOS)

Any ideas? 

````
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
       at com.airbnb.lottie.LottieComposition$Factory.parseLayers(LottieComposition.java:200)
       at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:194)
       at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:17)
       at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:7)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
````

**Comment by nehvaleem** [comment]
uh... um well...

It was totally all my fault. I've misunderstood whole thing and i've installed both lottie for android/ios and then lottie-react-native (as it supposed to be only the wrapper). This was cause of my problems. When I reverted changes and installed only lottie-react-native it started to work just fine :)
